{
    'target_service': 'identity',
    'status': 404,
    'code': 'NotAuthorizedOrNotFound',
    'opc-request-id': 'EF2FC4FA55944C20AEA0FB66B1538B82/35E35D4673DFBFC448C80A7E22949F33/2B8158A6550BC1CC744A786518DE6FFA',
    'message': 'Authorization failed or requested resource not found',
    'operation_name': 'list_users',
    'timestamp': '2024-01-09T19:34:28.432524+00:00',
    'client_version': 'Oracle-PythonSDK/2.118.1',
    'request_endpoint': 'GET https://identity.ca-toronto-1.oci.oraclecloud.com/20160918/users',
    'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.',
    'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_notauthorizedornotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/identity/20160918/User/ListUsers for details on this operation's requirements. If you are unable to resolve this identity issue, please contact Oracle support and provide them this full error message."
}